server:
  port: 9002
  servlet:
    context-path: /SpringBoot-Test
spring:
  application:
    name: SpringBoot-Test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testone?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: wj960323

data:
  id: 1
  name: 张三
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.model
logging:
  level: debug
pagehelper:
  reasonable: true
